name: Build Docker Images

on:
  push:
    branches:
    - master

jobs:
  trigger-build:
    uses: theaters2026/workflows/.github/workflows/buildah-build.yaml@main
    with:
      image-name: ${{ github.repository }}/backend
    secrets:
      personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  trigger-cleanup:
    needs: [ trigger-build ]
    uses: theaters2026/workflows/.github/workflows/clean-registry.yaml@main
    with:
      owner: ${{ github.repository_owner }}
      repository: backend
      package: backend/backend
      keep_n_tagged: 2
      dry_run: true
    secrets:
      personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  deploy:
    needs: [ trigger-cleanup ]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to environment
      run: |
        echo "Deploying application"
